export * from './dashboardScreen';
export * from './walletScreen';
export * from './qrCodeScreen';
export * from './profileScreen';
export * from './menuScreen';
export * from './personalDetailScreen'
export * from './addressScreen'
export * from './bankAccountScreen'
export * from './languageScreen'
export * from './passwordAndSecurityScreen'
export * from './userGuideScreen'
export * from './supportScreen'
export * from './termsAndConditionsScreen'
export * from './privacyPolicyScreen'